services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_contatos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: contatos
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_contatos
    restart: always
    ports:
      - "8081:80"
    environment:
      VUE_APP_API_BASE: "http://api:8000/api"
    depends_on:
      - api

  db:
    image: mysql:8.0
    container_name: mysql_contatos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contatos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_contatos
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
